### ISSUE TITLE
用例参数问题

### ISSUE THREAD

**Issue by Byyyi** [wu-clan/httpfpt#172]
业务接口校验的token是每次请求实时计算的，大概是key+secret+一些固定值计算并放入header中，目前看文档都是固定的文件，没有头绪怎么处理

**Comment by wu-clan** [comment]
首先，编写 token 生成函数

1. （非破坏性）可以尝试使用 hook 变量，并在每个用例文件中手动定义 config/headers 参数
2. （破坏性）添加一个新的自动授权方式，需要更新 auth.yaml && 文件解析, enum 类型, headers 解析
