### ISSUE TITLE
断言问题

### ISSUE THREAD

**Issue by shandudu** [wu-clan/httpfpt#173]
- assert: assert ${r_msg2} == pm.response.get('json').get('msg')
断言这样写时代码，format_assert_text = 'assert 操作成功 == 操作成功' 后续执行exec(format_assert_text)会报错，
错误是  name '操作成功' is not defined

**Comment by wu-clan** [comment]
在断言文件中搜索代码`response_value = eval(f'{response}.{use_code}')`，将 `eval` 方法替换为`literal_eval` 是否能解决您的问题？

**Comment by shandudu** [comment]
这样的话 获取 ['assert', '200', '==', "pm.response.get('status_code')"]  status_code时会报错

**Comment by wu-clan** [comment]
根据文档中的示例，请尝试`assert '${r_msg2}' == str(pm.response.get('json').get('msg'))`
